# .github/workflows/release-please.yml

name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create Release PR and GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

  update-homebrew:
    name: Update Homebrew Formula
    needs: release-please
    if: ${{ github.event.release.tag_name != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DevAIccelerate
        uses: actions/checkout@v3

      - name: Set release variables
        id: vars
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "TAR_URL=https://github.com/${{ github.repository }}/archive/refs/tags/${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_ENV

      - name: Calculate SHA256 of release tarball
        run: |
          curl -L "$TAR_URL" -o devai.tar.gz
          echo "TAR_SHA=$(shasum -a 256 devai.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Clone Homebrew Tap repo
        uses: actions/checkout@v3
        with:
          repository: msualp/homebrew-devai
          token: ${{ secrets.DEVAI_BOT_GITHUB_TOKEN }}
          path: tap

      - name: Update Formula/devai.rb
        run: |
          cat > tap/Formula/devai.rb <<EOF
class Devai < Formula
  desc "DevAIccelerate CLI Toolkit for AI-powered developer workflows"
  homepage "https://github.com/msualp/DevAIccelerate"
  url "$TAR_URL"
  sha256 "$TAR_SHA"
  license "MIT"
  version "$RELEASE_VERSION"

  depends_on "bash"
  depends_on "gum"
  depends_on "yq"
  depends_on "go-task/tap/go-task"

  def install
    bin.install "devai/bin/dai.sh" => "dai"
  end

  test do
    system "#{bin}/dai", "--version"
  end
end
EOF

      - name: Commit and push to Homebrew tap
        run: |
          cd tap
          git config user.name "DevAI Bot"
          git config user.email "bot@devai.ai"
          git add Formula/devai.rb
          git commit -m "Update formula for $RELEASE_VERSION"
          git push

